/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame.internals;

import entitys.Producto;
import static frame.Menu.listaProductos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julan
 */
public class PorPrecio extends javax.swing.JInternalFrame {
private DefaultTableModel modelo = new DefaultTableModel (){
        public boolean esCeldaEditable(int f, int c){
            //este metodo retorna v o f si la celda en la que esta es editable o no
            return false;
        }
    };
    /**
     * Creates new form PorPrecio
     */
    public PorPrecio() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfEntre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfHasta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaPrecio = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setText("Lista por Precio");

        jLabel2.setText(" Entre:   $");

        jtfEntre.setText("0.00");
        jtfEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEntreActionPerformed(evt);
            }
        });
        jtfEntre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEntreKeyReleased(evt);
            }
        });

        jLabel3.setText("y    $");

        jtfHasta.setText("0.00");
        jtfHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHastaActionPerformed(evt);
            }
        });

        jtTablaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTablaPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEntreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEntreActionPerformed

    private void jtfEntreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEntreKeyReleased
        borrarFilas();
        String x=jtfEntre.getText();
        String z=jtfHasta.getText();
        double entre,hasta = 0;
        
        try{
            entre=Double.parseDouble(x);
            hasta=Double.parseDouble(z);
        }catch(NumberFormatException ex){
            return;
        }
       for(Producto producto: listaProductos){
                double precio=producto.getPrecio();
            if(precio >= entre && precio <= hasta){
                modelo.addRow(new Object[]{producto.getCodigo(),producto.getDescripcion(),producto.getPrecio(),producto.getStock()});
            }
       }       
    }//GEN-LAST:event_jtfEntreKeyReleased

    private void jtfHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHastaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTablaPrecio;
    private javax.swing.JTextField jtfEntre;
    private javax.swing.JTextField jtfHasta;
    // End of variables declaration//GEN-END:variables
    private void armarCabecera(){
        modelo.addColumn("Código");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtTablaPrecio.setModel(modelo);
    }
    private void borrarFilas(){
        //este metodo borra las filas de productos en el buscador
        int f=jtTablaPrecio.getRowCount()-1; //cuenta las filas -1
        for(;f>=0;f--){ //inicializa f arriba
            modelo.removeRow(f);
        }
    }
}
